# -----------------------------------------------------
# Monitor Setup
# name: "Default"
# -----------------------------------------------------

#monitor=,preferred,auto,1
monitor=DP-1, 3840x2160, 1440x200, 1
monitor=DP-2, 2560x1440, 0x0, 1, transform, 3 
